// Données de seed — racines trilitères réelles (cf. PROJET.md §14)
// Le slug est régénéré par le hook pre('validate') du modèle Root à l'insertion.
//
// Chaque entrée contient aussi `vowelMadi` et `vowelMudari` :
//   - vowelMadi  : voyelle de la deuxième radicale au passé (a, i, u)
//   - vowelMudari: voyelle de la deuxième radicale au présent (a, i, u)
// Ces voyelles servent au générateur de words.data.js à produire les
// conjugaisons correctes. Voir scripts/generateWords.js pour la logique.

export const rootsData = [
  { letters: ['ك', 'ت', 'ب'], meaningFr: 'écrire', meaningEn: 'to write', meaningAr: 'الكتابة', transliteration: 'k-t-b', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['د', 'ر', 'س'], meaningFr: 'étudier, apprendre', meaningEn: 'to study', meaningAr: 'الدراسة', transliteration: 'd-r-s', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ع', 'ل', 'م'], meaningFr: 'savoir, connaître', meaningEn: 'to know', meaningAr: 'العِلم', transliteration: 'ʿ-l-m', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ك', 'س', 'ر'], meaningFr: 'casser, briser', meaningEn: 'to break', meaningAr: 'الكَسر', transliteration: 'k-s-r', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ف', 'ت', 'ح'], meaningFr: 'ouvrir', meaningEn: 'to open', meaningAr: 'الفَتح', transliteration: 'f-t-ḥ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ج', 'م', 'ل'], meaningFr: 'être beau', meaningEn: 'to be beautiful', meaningAr: 'الجَمال', transliteration: 'j-m-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ش', 'ر', 'ب'], meaningFr: 'boire', meaningEn: 'to drink', meaningAr: 'الشُّرب', transliteration: 'sh-r-b', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['أ', 'ك', 'ل'], meaningFr: 'manger', meaningEn: 'to eat', meaningAr: 'الأَكل', transliteration: 'ʾ-k-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ذ', 'ه', 'ب'], meaningFr: 'aller', meaningEn: 'to go', meaningAr: 'الذَّهاب', transliteration: 'dh-h-b', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ر', 'ج', 'ع'], meaningFr: 'retourner', meaningEn: 'to return', meaningAr: 'الرُّجوع', transliteration: 'r-j-ʿ', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['س', 'ك', 'ن'], meaningFr: 'habiter', meaningEn: 'to dwell', meaningAr: 'السُّكنى', transliteration: 's-k-n', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['خ', 'ر', 'ج'], meaningFr: 'sortir', meaningEn: 'to exit', meaningAr: 'الخُروج', transliteration: 'kh-r-j', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['د', 'خ', 'ل'], meaningFr: 'entrer', meaningEn: 'to enter', meaningAr: 'الدُّخول', transliteration: 'd-kh-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ج', 'ل', 'س'], meaningFr: "s'asseoir", meaningEn: 'to sit', meaningAr: 'الجُلوس', transliteration: 'j-l-s', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ل', 'ع', 'ب'], meaningFr: 'jouer', meaningEn: 'to play', meaningAr: 'اللَّعِب', transliteration: 'l-ʿ-b', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ض', 'ر', 'ب'], meaningFr: 'frapper', meaningEn: 'to hit', meaningAr: 'الضَّرب', transliteration: 'ḍ-r-b', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['س', 'م', 'ع'], meaningFr: 'entendre, écouter', meaningEn: 'to hear', meaningAr: 'السَّمع', transliteration: 's-m-ʿ', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ن', 'ظ', 'ر'], meaningFr: 'regarder', meaningEn: 'to look', meaningAr: 'النَّظر', transliteration: 'n-ẓ-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ع', 'م', 'ل'], meaningFr: 'faire, travailler', meaningEn: 'to work, to do', meaningAr: 'العَمَل', transliteration: 'ʿ-m-l', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ف', 'ع', 'ل'], meaningFr: 'faire', meaningEn: 'to do', meaningAr: 'الفِعل', transliteration: 'f-ʿ-l', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ق', 'و', 'ل'], meaningFr: 'dire', meaningEn: 'to say', meaningAr: 'القَول', transliteration: 'q-w-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ك', 'ث', 'ر'], meaningFr: 'être nombreux', meaningEn: 'to be many', meaningAr: 'الكَثرة', transliteration: 'k-th-r', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ق', 'ل', 'ل'], meaningFr: 'être peu', meaningEn: 'to be few', meaningAr: 'القِلَّة', transliteration: 'q-l-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ك', 'ب', 'ر'], meaningFr: 'être grand', meaningEn: 'to be big', meaningAr: 'الكِبَر', transliteration: 'k-b-r', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ص', 'غ', 'ر'], meaningFr: 'être petit', meaningEn: 'to be small', meaningAr: 'الصِّغَر', transliteration: 'ṣ-gh-r', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ط', 'و', 'ل'], meaningFr: 'être long', meaningEn: 'to be long', meaningAr: 'الطُّول', transliteration: 'ṭ-w-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ق', 'ص', 'ر'], meaningFr: 'être court', meaningEn: 'to be short', meaningAr: 'القِصَر', transliteration: 'q-ṣ-r', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ق', 'ر', 'ب'], meaningFr: 'être proche', meaningEn: 'to be near', meaningAr: 'القُرب', transliteration: 'q-r-b', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ب', 'ع', 'د'], meaningFr: 'être loin', meaningEn: 'to be far', meaningAr: 'البُعد', transliteration: 'b-ʿ-d', vowelMadi: 'u', vowelMudari: 'u' },
  { letters: ['ر', 'ك', 'ب'], meaningFr: 'monter, chevaucher', meaningEn: 'to ride', meaningAr: 'الرُّكوب', transliteration: 'r-k-b', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ن', 'ز', 'ل'], meaningFr: 'descendre', meaningEn: 'to descend', meaningAr: 'النُّزول', transliteration: 'n-z-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ر', 'ف', 'ع'], meaningFr: 'élever, lever', meaningEn: 'to raise', meaningAr: 'الرَّفع', transliteration: 'r-f-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['و', 'ض', 'ع'], meaningFr: 'poser, placer', meaningEn: 'to place', meaningAr: 'الوَضع', transliteration: 'w-ḍ-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ج', 'ع', 'ل'], meaningFr: 'rendre, faire devenir', meaningEn: 'to make', meaningAr: 'الجَعل', transliteration: 'j-ʿ-l', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ت', 'ر', 'ك'], meaningFr: 'laisser, abandonner', meaningEn: 'to leave', meaningAr: 'التَّرك', transliteration: 't-r-k', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ر', 'س', 'ل'], meaningFr: 'envoyer', meaningEn: 'to send', meaningAr: 'الإرسال', transliteration: 'r-s-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['و', 'ص', 'ل'], meaningFr: 'arriver, parvenir', meaningEn: 'to arrive', meaningAr: 'الوُصول', transliteration: 'w-ṣ-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ق', 'ط', 'ع'], meaningFr: 'couper', meaningEn: 'to cut', meaningAr: 'القَطع', transliteration: 'q-ṭ-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['غ', 'س', 'ل'], meaningFr: 'laver', meaningEn: 'to wash', meaningAr: 'الغَسل', transliteration: 'gh-s-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ل', 'ب', 'س'], meaningFr: 'porter, vêtir', meaningEn: 'to wear', meaningAr: 'اللُّبس', transliteration: 'l-b-s', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ط', 'ب', 'خ'], meaningFr: 'cuisiner', meaningEn: 'to cook', meaningAr: 'الطَّبخ', transliteration: 'ṭ-b-kh', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['خ', 'ب', 'ز'], meaningFr: 'cuire le pain', meaningEn: 'to bake bread', meaningAr: 'الخَبز', transliteration: 'kh-b-z', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ز', 'ر', 'ع'], meaningFr: 'semer, planter', meaningEn: 'to plant', meaningAr: 'الزَّرع', transliteration: 'z-r-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ح', 'ص', 'د'], meaningFr: 'moissonner', meaningEn: 'to harvest', meaningAr: 'الحَصاد', transliteration: 'ḥ-ṣ-d', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ص', 'ن', 'ع'], meaningFr: 'fabriquer', meaningEn: 'to make, manufacture', meaningAr: 'الصِّناعة', transliteration: 'ṣ-n-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ب', 'ن', 'ي'], meaningFr: 'construire', meaningEn: 'to build', meaningAr: 'البِناء', transliteration: 'b-n-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ه', 'د', 'م'], meaningFr: 'démolir', meaningEn: 'to demolish', meaningAr: 'الهَدم', transliteration: 'h-d-m', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ف', 'ك', 'ر'], meaningFr: 'réfléchir, penser', meaningEn: 'to think', meaningAr: 'التَّفكير', transliteration: 'f-k-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ذ', 'ك', 'ر'], meaningFr: 'se rappeler, mentionner', meaningEn: 'to remember', meaningAr: 'الذِّكر', transliteration: 'dh-k-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ن', 'س', 'ي'], meaningFr: 'oublier', meaningEn: 'to forget', meaningAr: 'النِّسيان', transliteration: 'n-s-y', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ح', 'ف', 'ظ'], meaningFr: 'mémoriser, garder', meaningEn: 'to memorize, keep', meaningAr: 'الحِفظ', transliteration: 'ḥ-f-ẓ', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ع', 'ر', 'ف'], meaningFr: 'connaître', meaningEn: 'to know (acquaint)', meaningAr: 'المَعرفة', transliteration: 'ʿ-r-f', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ج', 'ه', 'ل'], meaningFr: 'ignorer', meaningEn: 'to be ignorant', meaningAr: 'الجَهل', transliteration: 'j-h-l', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ف', 'ه', 'م'], meaningFr: 'comprendre', meaningEn: 'to understand', meaningAr: 'الفَهم', transliteration: 'f-h-m', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ش', 'ك', 'ر'], meaningFr: 'remercier', meaningEn: 'to thank', meaningAr: 'الشُّكر', transliteration: 'sh-k-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ح', 'م', 'د'], meaningFr: 'louer (Dieu)', meaningEn: 'to praise', meaningAr: 'الحَمد', transliteration: 'ḥ-m-d', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ع', 'ب', 'د'], meaningFr: 'adorer, servir', meaningEn: 'to worship', meaningAr: 'العِبادة', transliteration: 'ʿ-b-d', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ص', 'ل', 'ي'], meaningFr: 'prier', meaningEn: 'to pray', meaningAr: 'الصَّلاة', transliteration: 'ṣ-l-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ص', 'و', 'م'], meaningFr: 'jeûner', meaningEn: 'to fast', meaningAr: 'الصِّيام', transliteration: 'ṣ-w-m', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ح', 'ج', 'ج'], meaningFr: 'pèleriner', meaningEn: 'to pilgrimage', meaningAr: 'الحَجّ', transliteration: 'ḥ-j-j', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ق', 'ر', 'أ'], meaningFr: 'lire', meaningEn: 'to read', meaningAr: 'القِراءة', transliteration: 'q-r-ʾ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['س', 'أ', 'ل'], meaningFr: 'demander, questionner', meaningEn: 'to ask', meaningAr: 'السُّؤال', transliteration: 's-ʾ-l', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ج', 'و', 'ب'], meaningFr: 'répondre', meaningEn: 'to answer', meaningAr: 'الجَواب', transliteration: 'j-w-b', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ك', 'ل', 'م'], meaningFr: 'parler', meaningEn: 'to speak', meaningAr: 'الكَلام', transliteration: 'k-l-m', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ص', 'م', 'ت'], meaningFr: 'se taire', meaningEn: 'to be silent', meaningAr: 'الصَّمت', transliteration: 'ṣ-m-t', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ض', 'ح', 'ك'], meaningFr: 'rire', meaningEn: 'to laugh', meaningAr: 'الضَّحِك', transliteration: 'ḍ-ḥ-k', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ب', 'ك', 'ي'], meaningFr: 'pleurer', meaningEn: 'to cry', meaningAr: 'البُكاء', transliteration: 'b-k-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ن', 'و', 'م'], meaningFr: 'dormir', meaningEn: 'to sleep', meaningAr: 'النَّوم', transliteration: 'n-w-m', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ي', 'ق', 'ظ'], meaningFr: "s'éveiller", meaningEn: 'to wake up', meaningAr: 'اليَقَظة', transliteration: 'y-q-ẓ', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ج', 'ر', 'ي'], meaningFr: 'courir', meaningEn: 'to run', meaningAr: 'الجَري', transliteration: 'j-r-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['م', 'ش', 'ي'], meaningFr: 'marcher', meaningEn: 'to walk', meaningAr: 'المَشي', transliteration: 'm-sh-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['و', 'ق', 'ف'], meaningFr: "s'arrêter, se tenir debout", meaningEn: 'to stand, stop', meaningAr: 'الوُقوف', transliteration: 'w-q-f', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ق', 'ع', 'د'], meaningFr: "s'asseoir, demeurer", meaningEn: 'to sit, stay', meaningAr: 'القُعود', transliteration: 'q-ʿ-d', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['س', 'ف', 'ر'], meaningFr: 'voyager', meaningEn: 'to travel', meaningAr: 'السَّفر', transliteration: 's-f-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ن', 'ص', 'ر'], meaningFr: 'aider, secourir', meaningEn: 'to help', meaningAr: 'النَّصر', transliteration: 'n-ṣ-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ظ', 'ل', 'م'], meaningFr: 'opprimer', meaningEn: 'to oppress', meaningAr: 'الظُّلم', transliteration: 'ẓ-l-m', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ع', 'د', 'ل'], meaningFr: 'être juste', meaningEn: 'to be just', meaningAr: 'العَدل', transliteration: 'ʿ-d-l', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ر', 'ح', 'م'], meaningFr: 'avoir pitié', meaningEn: 'to have mercy', meaningAr: 'الرَّحمة', transliteration: 'r-ḥ-m', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['غ', 'ف', 'ر'], meaningFr: 'pardonner', meaningEn: 'to forgive', meaningAr: 'المَغفِرة', transliteration: 'gh-f-r', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['س', 'ر', 'ق'], meaningFr: 'voler, dérober', meaningEn: 'to steal', meaningAr: 'السَّرِقة', transliteration: 's-r-q', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ك', 'ذ', 'ب'], meaningFr: 'mentir', meaningEn: 'to lie', meaningAr: 'الكَذِب', transliteration: 'k-dh-b', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ص', 'د', 'ق'], meaningFr: 'être véridique', meaningEn: 'to be truthful', meaningAr: 'الصِّدق', transliteration: 'ṣ-d-q', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['و', 'ع', 'د'], meaningFr: 'promettre', meaningEn: 'to promise', meaningAr: 'الوَعد', transliteration: 'w-ʿ-d', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['خ', 'ل', 'ق'], meaningFr: 'créer', meaningEn: 'to create', meaningAr: 'الخَلق', transliteration: 'kh-l-q', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['و', 'ل', 'د'], meaningFr: 'enfanter', meaningEn: 'to give birth', meaningAr: 'الوِلادة', transliteration: 'w-l-d', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['م', 'و', 'ت'], meaningFr: 'mourir', meaningEn: 'to die', meaningAr: 'المَوت', transliteration: 'm-w-t', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ح', 'ي', 'ي'], meaningFr: 'vivre', meaningEn: 'to live', meaningAr: 'الحَياة', transliteration: 'ḥ-y-y', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ق', 'ت', 'ل'], meaningFr: 'tuer', meaningEn: 'to kill', meaningAr: 'القَتل', transliteration: 'q-t-l', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['أ', 'م', 'ر'], meaningFr: 'ordonner', meaningEn: 'to command', meaningAr: 'الأَمر', transliteration: 'ʾ-m-r', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ن', 'ه', 'ي'], meaningFr: 'interdire', meaningEn: 'to forbid', meaningAr: 'النَّهي', transliteration: 'n-h-y', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ح', 'ك', 'م'], meaningFr: 'juger, gouverner', meaningEn: 'to judge, rule', meaningAr: 'الحُكم', transliteration: 'ḥ-k-m', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['م', 'ل', 'ك'], meaningFr: 'posséder, régner', meaningEn: 'to own, reign', meaningAr: 'المُلك', transliteration: 'm-l-k', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ب', 'ي', 'ع'], meaningFr: 'vendre', meaningEn: 'to sell', meaningAr: 'البَيع', transliteration: 'b-y-ʿ', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ش', 'ر', 'ي'], meaningFr: 'acheter', meaningEn: 'to buy', meaningAr: 'الشِّراء', transliteration: 'sh-r-y', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['د', 'ف', 'ع'], meaningFr: 'payer, pousser', meaningEn: 'to pay, push', meaningAr: 'الدَّفع', transliteration: 'd-f-ʿ', vowelMadi: 'a', vowelMudari: 'a' },
  { letters: ['ر', 'ب', 'ح'], meaningFr: 'gagner, profiter', meaningEn: 'to profit', meaningAr: 'الرِّبح', transliteration: 'r-b-ḥ', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['خ', 'س', 'ر'], meaningFr: 'perdre', meaningEn: 'to lose', meaningAr: 'الخُسران', transliteration: 'kh-s-r', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['و', 'ج', 'د'], meaningFr: 'trouver', meaningEn: 'to find', meaningAr: 'الوُجود', transliteration: 'w-j-d', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ف', 'ق', 'د'], meaningFr: 'perdre, manquer', meaningEn: 'to lose', meaningAr: 'الفُقدان', transliteration: 'f-q-d', vowelMadi: 'a', vowelMudari: 'i' },
  { letters: ['ط', 'ل', 'ب'], meaningFr: 'chercher, demander', meaningEn: 'to seek', meaningAr: 'الطَّلب', transliteration: 'ṭ-l-b', vowelMadi: 'a', vowelMudari: 'u' },
  { letters: ['ق', 'ب', 'ل'], meaningFr: 'accepter', meaningEn: 'to accept', meaningAr: 'القَبول', transliteration: 'q-b-l', vowelMadi: 'i', vowelMudari: 'a' },
  { letters: ['ر', 'ف', 'ض'], meaningFr: 'refuser', meaningEn: 'to refuse', meaningAr: 'الرَّفض', transliteration: 'r-f-ḍ', vowelMadi: 'a', vowelMudari: 'u' },
];

export default rootsData;
