// Données de seed — mots dérivés arabes vérifiés (cf. PROJET.md §7, §14)
// Chaque mot référence sa racine par son slug (3 lettres jointes par '-').
// L'enregistrement couvre les 7 types WORD_TYPES et les 3 tense (MADI/MUDARI/AMR).

export const wordsData = [
  // ───────── Racine ك-ت-ب (écrire) ─────────
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'كَتَبَ',
    transliteration: 'kataba',
    translationFr: 'il a écrit',
    translationEn: 'he wrote',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعَلَ',
    example: 'كَتَبَ الطَّالِبُ الدَّرْسَ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'يَكْتُبُ',
    transliteration: 'yaktubu',
    translationFr: 'il écrit',
    translationEn: 'he writes',
    type: 'VERB',
    tense: 'MUDARI',
    pattern: 'يَفْعُلُ',
    example: 'يَكْتُبُ رِسَالَةً إِلَى صَدِيقِهِ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'اُكْتُبْ',
    transliteration: 'uktub',
    translationFr: 'écris !',
    translationEn: 'write!',
    type: 'VERB',
    tense: 'AMR',
    pattern: 'اُفْعُلْ',
    example: 'اُكْتُبْ اسْمَكَ هُنَا.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'كِتَابَة',
    transliteration: 'kitāba',
    translationFr: "l'écriture",
    translationEn: 'writing',
    type: 'MASDAR',
    pattern: 'فِعَالَة',
    example: 'الكِتَابَةُ مَهَارَةٌ مُهِمَّةٌ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'كَاتِب',
    transliteration: 'kātib',
    translationFr: 'écrivain',
    translationEn: 'writer',
    type: 'ACTIVE_PART',
    pattern: 'فَاعِل',
    example: 'الكَاتِبُ مَشْهُورٌ فِي بَلَدِهِ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'مَكْتُوب',
    transliteration: 'maktūb',
    translationFr: 'écrit, lettre',
    translationEn: 'written, letter',
    type: 'PASSIVE_PART',
    pattern: 'مَفْعُول',
    example: 'هَذَا مَكْتُوبٌ بِخَطٍّ جَمِيلٍ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'مَكْتَب',
    transliteration: 'maktab',
    translationFr: 'bureau',
    translationEn: 'office, desk',
    type: 'NOUN_PLACE',
    pattern: 'مَفْعَل',
    example: 'يَعْمَلُ فِي المَكْتَبِ كُلَّ يَوْمٍ.',
  },
  {
    rootSlug: 'ك-ت-ب',
    arabic: 'مَكْتَبَة',
    transliteration: 'maktaba',
    translationFr: 'bibliothèque',
    translationEn: 'library',
    type: 'NOUN_PLACE',
    pattern: 'مَفْعَلَة',
    example: 'اسْتَعَرْتُ كِتَابًا مِنَ المَكْتَبَةِ.',
  },

  // ───────── Racine د-ر-س (étudier) ─────────
  {
    rootSlug: 'د-ر-س',
    arabic: 'دَرَسَ',
    transliteration: 'darasa',
    translationFr: 'il a étudié',
    translationEn: 'he studied',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعَلَ',
    example: 'دَرَسَ اللُّغَةَ العَرَبِيَّةَ.',
  },
  {
    rootSlug: 'د-ر-س',
    arabic: 'يَدْرُسُ',
    transliteration: 'yadrusu',
    translationFr: 'il étudie',
    translationEn: 'he studies',
    type: 'VERB',
    tense: 'MUDARI',
    pattern: 'يَفْعُلُ',
    example: 'يَدْرُسُ فِي الجَامِعَةِ.',
  },
  {
    rootSlug: 'د-ر-س',
    arabic: 'دِرَاسَة',
    transliteration: 'dirāsa',
    translationFr: "l'étude",
    translationEn: 'study',
    type: 'MASDAR',
    pattern: 'فِعَالَة',
    example: 'الدِّرَاسَةُ تَتَطَلَّبُ الصَّبْرَ.',
  },
  {
    rootSlug: 'د-ر-س',
    arabic: 'دَارِس',
    transliteration: 'dāris',
    translationFr: 'étudiant, celui qui étudie',
    translationEn: 'student, one who studies',
    type: 'ACTIVE_PART',
    pattern: 'فَاعِل',
    example: 'الدَّارِسُ مُجْتَهِدٌ.',
  },
  {
    rootSlug: 'د-ر-س',
    arabic: 'مَدْرُوس',
    transliteration: 'madrūs',
    translationFr: 'étudié',
    translationEn: 'studied',
    type: 'PASSIVE_PART',
    pattern: 'مَفْعُول',
    example: 'المَوْضُوعُ مَدْرُوسٌ بِعِنَايَةٍ.',
  },
  {
    rootSlug: 'د-ر-س',
    arabic: 'مَدْرَسَة',
    transliteration: 'madrasa',
    translationFr: 'école',
    translationEn: 'school',
    type: 'NOUN_PLACE',
    pattern: 'مَفْعَلَة',
    example: 'يَذْهَبُ الأَطْفَالُ إِلَى المَدْرَسَةِ.',
  },

  // ───────── Racine ع-ل-م (savoir) ─────────
  {
    rootSlug: 'ع-ل-م',
    arabic: 'عَلِمَ',
    transliteration: 'ʿalima',
    translationFr: 'il a su',
    translationEn: 'he knew',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعِلَ',
    example: 'عَلِمَ بِالخَبَرِ أَمْسِ.',
  },
  {
    rootSlug: 'ع-ل-م',
    arabic: 'اِعْلَمْ',
    transliteration: 'iʿlam',
    translationFr: 'sache !',
    translationEn: 'know!',
    type: 'VERB',
    tense: 'AMR',
    pattern: 'اِفْعَلْ',
    example: 'اِعْلَمْ أَنَّ العِلْمَ نُورٌ.',
  },
  {
    rootSlug: 'ع-ل-م',
    arabic: 'عِلْم',
    transliteration: 'ʿilm',
    translationFr: 'science, savoir',
    translationEn: 'science, knowledge',
    type: 'MASDAR',
    pattern: 'فِعْل',
    example: 'العِلْمُ يَرْفَعُ صَاحِبَهُ.',
  },
  {
    rootSlug: 'ع-ل-م',
    arabic: 'عَالِم',
    transliteration: 'ʿālim',
    translationFr: 'savant',
    translationEn: 'scholar, scientist',
    type: 'ACTIVE_PART',
    pattern: 'فَاعِل',
    example: 'العَالِمُ يَبْحَثُ عَنِ الحَقِيقَةِ.',
  },
  {
    rootSlug: 'ع-ل-م',
    arabic: 'مَعْلُوم',
    transliteration: 'maʿlūm',
    translationFr: 'connu, su',
    translationEn: 'known',
    type: 'PASSIVE_PART',
    pattern: 'مَفْعُول',
    example: 'الجَوَابُ مَعْلُومٌ لِلْجَمِيعِ.',
  },
  {
    rootSlug: 'ع-ل-م',
    arabic: 'أَعْلَم',
    transliteration: 'aʿlam',
    translationFr: 'le plus savant',
    translationEn: 'most knowledgeable',
    type: 'ELATIVE',
    pattern: 'أَفْعَل',
    example: 'هُوَ أَعْلَمُ النَّاسِ بِهَذَا الأَمْرِ.',
  },

  // ───────── Racine ك-س-ر (casser) ─────────
  {
    rootSlug: 'ك-س-ر',
    arabic: 'كَسَرَ',
    transliteration: 'kasara',
    translationFr: 'il a cassé',
    translationEn: 'he broke',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعَلَ',
    example: 'كَسَرَ الوَلَدُ الزُّجَاجَ.',
  },
  {
    rootSlug: 'ك-س-ر',
    arabic: 'يَكْسِرُ',
    transliteration: 'yaksiru',
    translationFr: 'il casse',
    translationEn: 'he breaks',
    type: 'VERB',
    tense: 'MUDARI',
    pattern: 'يَفْعِلُ',
    example: 'يَكْسِرُ الجَوْزَ بِيَدِهِ.',
  },
  {
    rootSlug: 'ك-س-ر',
    arabic: 'كَسْر',
    transliteration: 'kasr',
    translationFr: 'le fait de casser, fracture',
    translationEn: 'breaking, fracture',
    type: 'MASDAR',
    pattern: 'فَعْل',
    example: 'كَسْرُ العَظْمِ مُؤْلِمٌ.',
  },
  {
    rootSlug: 'ك-س-ر',
    arabic: 'كَاسِر',
    transliteration: 'kāsir',
    translationFr: 'celui qui casse',
    translationEn: 'breaker',
    type: 'ACTIVE_PART',
    pattern: 'فَاعِل',
    example: 'الكَاسِرُ يَدْفَعُ ثَمَنَ الضَّرَرِ.',
  },
  {
    rootSlug: 'ك-س-ر',
    arabic: 'مَكْسُور',
    transliteration: 'maksūr',
    translationFr: 'cassé',
    translationEn: 'broken',
    type: 'PASSIVE_PART',
    pattern: 'مَفْعُول',
    example: 'الكُوبُ مَكْسُورٌ.',
  },
  {
    rootSlug: 'ك-س-ر',
    arabic: 'مِكْسَار',
    transliteration: 'miksār',
    translationFr: 'instrument pour casser',
    translationEn: 'breaking tool',
    type: 'NOUN_TOOL',
    pattern: 'مِفْعَال',
    example: 'يَسْتَخْدِمُ المِكْسَارَ لِتَكْسِيرِ الحِجَارَةِ.',
  },

  // ───────── Racine ف-ت-ح (ouvrir) ─────────
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'فَتَحَ',
    transliteration: 'fataḥa',
    translationFr: 'il a ouvert',
    translationEn: 'he opened',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعَلَ',
    example: 'فَتَحَ البَابَ بِالمِفْتَاحِ.',
  },
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'اِفْتَحْ',
    transliteration: 'iftaḥ',
    translationFr: 'ouvre !',
    translationEn: 'open!',
    type: 'VERB',
    tense: 'AMR',
    pattern: 'اِفْعَلْ',
    example: 'اِفْتَحِ النَّافِذَةَ مِنْ فَضْلِكَ.',
  },
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'فَتْح',
    transliteration: 'fatḥ',
    translationFr: "l'ouverture, la conquête",
    translationEn: 'opening, conquest',
    type: 'MASDAR',
    pattern: 'فَعْل',
    example: 'فَتْحُ الأَبْوَابِ صَبَاحًا.',
  },
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'فَاتِح',
    transliteration: 'fātiḥ',
    translationFr: 'celui qui ouvre, conquérant',
    translationEn: 'opener, conqueror',
    type: 'ACTIVE_PART',
    pattern: 'فَاعِل',
    example: 'الفَاتِحُ دَخَلَ المَدِينَةَ.',
  },
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'مَفْتُوح',
    transliteration: 'maftūḥ',
    translationFr: 'ouvert',
    translationEn: 'open, opened',
    type: 'PASSIVE_PART',
    pattern: 'مَفْعُول',
    example: 'البَابُ مَفْتُوحٌ.',
  },
  {
    rootSlug: 'ف-ت-ح',
    arabic: 'مِفْتَاح',
    transliteration: 'miftāḥ',
    translationFr: 'clé',
    translationEn: 'key',
    type: 'NOUN_TOOL',
    pattern: 'مِفْعَال',
    example: 'فَقَدْتُ مِفْتَاحَ السَّيَّارَةِ.',
  },

  // ───────── Racine ج-م-ل (être beau) ─────────
  {
    rootSlug: 'ج-م-ل',
    arabic: 'جَمُلَ',
    transliteration: 'jamula',
    translationFr: 'il fut beau',
    translationEn: 'he was beautiful',
    type: 'VERB',
    tense: 'MADI',
    pattern: 'فَعُلَ',
    example: 'جَمُلَ المَنْظَرُ بَعْدَ المَطَرِ.',
  },
  {
    rootSlug: 'ج-م-ل',
    arabic: 'يَجْمُلُ',
    transliteration: 'yajmulu',
    translationFr: 'il est beau',
    translationEn: 'it is beautiful',
    type: 'VERB',
    tense: 'MUDARI',
    pattern: 'يَفْعُلُ',
    example: 'يَجْمُلُ الوَجْهُ بِالابْتِسَامَةِ.',
  },
  {
    rootSlug: 'ج-م-ل',
    arabic: 'جَمَال',
    transliteration: 'jamāl',
    translationFr: 'la beauté',
    translationEn: 'beauty',
    type: 'MASDAR',
    pattern: 'فَعَال',
    example: 'جَمَالُ الطَّبِيعَةِ يُبْهِرُ النَّاظِرَ.',
  },
  {
    rootSlug: 'ج-م-ل',
    arabic: 'أَجْمَل',
    transliteration: 'ajmal',
    translationFr: 'le plus beau',
    translationEn: 'most beautiful',
    type: 'ELATIVE',
    pattern: 'أَفْعَل',
    example: 'هَذِهِ أَجْمَلُ حَدِيقَةٍ فِي المَدِينَةِ.',
  },
];

export default wordsData;
